const char * imagenet_classes[] {
"tench, Tinca tinca",
"goldfish, Carassius auratus",
"great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
"tiger shark, Galeocerdo cuvieri",
"hammerhead, hammerhead shark",
"electric ray, crampfish, numbfish, torpedo",
"stingray",
"cock",
"hen",
"ostrich, Struthio camelus",
"brambling, Fringilla montifringilla",
"goldfinch, Carduelis carduelis",
"house finch, linnet, Carpodacus mexicanus",
"junco, snowbird",
"indigo bunting, indigo finch, indigo bird, Passerina cyanea",
"robin, American robin, Turdus migratorius",
"bulbul",
"jay",
"magpie",
"chickadee",
"water ouzel, dipper",
"kite",
"bald eagle, American eagle, Haliaeetus leucocephalus",
"vulture",
"great grey owl, great gray owl, Strix nebulosa",
"European fire salamander, Salamandra salamandra",
"common newt, Triturus vulgaris",
"eft",
"spotted salamander, Ambystoma maculatum",
"axolotl, mud puppy, Ambystoma mexicanum",
"bullfrog, Rana catesbeiana",
"tree frog, tree-frog",
"tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
"loggerhead, loggerhead turtle, Caretta caretta",
"leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
"mud turtle",
"terrapin",
"box turtle, box tortoise",
"banded gecko",
"common iguana, iguana, Iguana iguana",
"American chameleon, anole, Anolis carolinensis",
"whiptail, whiptail lizard",
"agama",
"frilled lizard, Chlamydosaurus kingi",
"alligator lizard",
"Gila monster, Heloderma suspectum",
"green lizard, Lacerta viridis",
"African chameleon, Chamaeleo chamaeleon",
"Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
"African crocodile, Nile crocodile, Crocodylus niloticus",
"American alligator, Alligator mississipiensis",
"triceratops",
"thunder snake, worm snake, Carphophis amoenus",
"ringneck snake, ring-necked snake, ring snake",
"hognose snake, puff adder, sand viper",
"green snake, grass snake",
"king snake, kingsnake",
"garter snake, grass snake",
"water snake",
"vine snake",
"night snake, Hypsiglena torquata",
"boa constrictor, Constrictor constrictor",
"rock python, rock snake, Python sebae",
"Indian cobra, Naja naja",
"green mamba",
"sea snake",
"horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
"diamondback, diamondback rattlesnake, Crotalus adamanteus",
"sidewinder, horned rattlesnake, Crotalus cerastes",
"trilobite",
"harvestman, daddy longlegs, Phalangium opilio",
"scorpion",
"black and gold garden spider, Argiope aurantia",
"barn spider, Araneus cavaticus",
"garden spider, Aranea diademata",
"black widow, Latrodectus mactans",
"tarantula",
"wolf spider, hunting spider",
"tick",
"centipede",
"black grouse",
"ptarmigan",
"ruffed grouse, partridge, Bonasa umbellus",
"prairie chicken, prairie grouse, prairie fowl",
"peacock",
"quail",
"partridge",
"African grey, African gray, Psittacus erithacus",
"macaw",
"sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
"lorikeet",
"coucal",
"bee eater",
"hornbill",
"hummingbird",
"jacamar",
"toucan",
"drake",
"red-breasted merganser, Mergus serrator",
"goose",
"black swan, Cygnus atratus",
"tusker",
"echidna, spiny anteater, anteater",
"platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus",
"wallaby, brush kangaroo",
"koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus",
"wombat",
"jellyfish",
"sea anemone, anemone",
"brain coral",
"flatworm, platyhelminth",
"nematode, nematode worm, roundworm",
"conch",
"snail",
"slug",
"sea slug, nudibranch",
"chiton, coat-of-mail shell, sea cradle, polyplacophore",
"chambered nautilus, pearly nautilus, nautilus",
"Dungeness crab, Cancer magister",
"rock crab, Cancer irroratus",
"fiddler crab",
"king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica",
"American lobster, Northern lobster, Maine lobster, Homarus americanus",
"spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
"crayfish, crawfish, crawdad, crawdaddy",
"hermit crab",
"isopod",
"white stork, Ciconia ciconia",
"black stork, Ciconia nigra",
"spoonbill",
"flamingo",
"little blue heron, Egretta caerulea",
"American egret, great white heron, Egretta albus",
"bittern",
"crane",
"limpkin, Aramus pictus",
"European gallinule, Porphyrio porphyrio",
"American coot, marsh hen, mud hen, water hen, Fulica americana",
"bustard",
"ruddy turnstone, Arenaria interpres",
"red-backed sandpiper, dunlin, Erolia alpina",
"redshank, Tringa totanus",
"dowitcher",
"oystercatcher, oyster catcher",
"pelican",
"king penguin, Aptenodytes patagonica",
"albatross, mollymawk",
"grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus",
"killer whale, killer, orca, grampus, sea wolf, Orcinus orca",
"dugong, Dugong dugon",
"sea lion",
"Chihuahua",
"Japanese spaniel",
"Maltese dog, Maltese terrier, Maltese",
"Pekinese, Pekingese, Peke",
"Shih-Tzu",
"Blenheim spaniel",
"papillon",
"toy terrier",
"Rhodesian ridgeback",
"Afghan hound, Afghan",
"basset, basset hound",
"beagle",
"bloodhound, sleuthhound",
"bluetick",
"black-and-tan coonhound",
"Walker hound, Walker foxhound",
"English foxhound",
"redbone",
"borzoi, Russian wolfhound",
"Irish wolfhound",
"Italian greyhound",
"whippet",
"Ibizan hound, Ibizan Podenco",
"Norwegian elkhound, elkhound",
"otterhound, otter hound",
"Saluki, gazelle hound",
"Scottish deerhound, deerhound",
"Weimaraner",
"Staffordshire bullterrier, Staffordshire bull terrier",
"American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier",
"Bedlington terrier",
"Border terrier",
"Kerry blue terrier",
"Irish terrier",
"Norfolk terrier",
"Norwich terrier",
"Yorkshire terrier",
"wire-haired fox terrier",
"Lakeland terrier",
"Sealyham terrier, Sealyham",
"Airedale, Airedale terrier",
"cairn, cairn terrier",
"Australian terrier",
"Dandie Dinmont, Dandie Dinmont terrier",
"Boston bull, Boston terrier",
"miniature schnauzer",
"giant schnauzer",
"standard schnauzer",
"Scotch terrier, Scottish terrier, Scottie",
"Tibetan terrier, chrysanthemum dog",
"silky terrier, Sydney silky",
"soft-coated wheaten terrier",
"West Highland white terrier",
"Lhasa, Lhasa apso",
"flat-coated retriever",
"curly-coated retriever",
"golden retriever",
"Labrador retriever",
"Chesapeake Bay retriever",
"German short-haired pointer",
"vizsla, Hungarian pointer",
"English setter",
"Irish setter, red setter",
"Gordon setter",
"Brittany spaniel",
"clumber, clumber spaniel",
"English springer, English springer spaniel",
"Welsh springer spaniel",
"cocker spaniel, English cocker spaniel, cocker",
"Sussex spaniel",
"Irish water spaniel",
"kuvasz",
"schipperke",
"groenendael",
"malinois",
"briard",
"kelpie",
"komondor",
"Old English sheepdog, bobtail",
"Shetland sheepdog, Shetland sheep dog, Shetland",
"collie",
"Border collie",
"Bouvier des Flandres, Bouviers des Flandres",
"Rottweiler",
"German shepherd, German shepherd dog, German police dog, alsatian",
"Doberman, Doberman pinscher",
"miniature pinscher",
"Greater Swiss Mountain dog",
"Bernese mountain dog",
"Appenzeller",
"EntleBucher",
"boxer",
"bull mastiff",
"Tibetan mastiff",
"French bulldog",
"Great Dane",
"Saint Bernard, St Bernard",
"Eskimo dog, husky",
"malamute, malemute, Alaskan malamute",
"Siberian husky",
"dalmatian, coach dog, carriage dog",
"affenpinscher, monkey pinscher, monkey dog",
"basenji",
"pug, pug-dog",
"Leonberg",
"Newfoundland, Newfoundland dog",
"Great Pyrenees",
"Samoyed, Samoyede",
"Pomeranian",
"chow, chow chow",
"keeshond",
"Brabancon griffon",
"Pembroke, Pembroke Welsh corgi",
"Cardigan, Cardigan Welsh corgi",
"toy poodle",
"miniature poodle",
"standard poodle",
"Mexican hairless",
"timber wolf, grey wolf, gray wolf, Canis lupus",
"white wolf, Arctic wolf, Canis lupus tundrarum",
"red wolf, maned wolf, Canis rufus, Canis niger",
"coyote, prairie wolf, brush wolf, Canis latrans",
"dingo, warrigal, warragal, Canis dingo",
"dhole, Cuon alpinus",
"African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus",
"hyena, hyaena",
"red fox, Vulpes vulpes",
"kit fox, Vulpes macrotis",
"Arctic fox, white fox, Alopex lagopus",
"grey fox, gray fox, Urocyon cinereoargenteus",
"tabby, tabby cat",
"tiger cat",
"Persian cat",
"Siamese cat, Siamese",
"Egyptian cat",
"cougar, puma, catamount, mountain lion, painter, panther, Felis concolor",
"lynx, catamount",
"leopard, Panthera pardus",
"snow leopard, ounce, Panthera uncia",
"jaguar, panther, Panthera onca, Felis onca",
"lion, king of beasts, Panthera leo",
"tiger, Panthera tigris",
"cheetah, chetah, Acinonyx jubatus",
"brown bear, bruin, Ursus arctos",
"American black bear, black bear, Ursus americanus, Euarctos americanus",
"ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus",
"sloth bear, Melursus ursinus, Ursus ursinus",
"mongoose",
"meerkat, mierkat",
"tiger beetle",
"ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle",
"ground beetle, carabid beetle",
"long-horned beetle, longicorn, longicorn beetle",
"leaf beetle, chrysomelid",
"dung beetle",
"rhinoceros beetle",
"weevil",
"fly",
"bee",
"ant, emmet, pismire",
"grasshopper, hopper",
"cricket",
"walking stick, walkingstick, stick insect",
"cockroach, roach",
"mantis, mantid",
"cicada, cicala",
"leafhopper",
"lacewing, lacewing fly",
"dragonfly, darning needle, devil's darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk",
"damselfly",
"admiral",
"ringlet, ringlet butterfly",
"monarch, monarch butterfly, milkweed butterfly, Danaus plexippus",
"cabbage butterfly",
"sulphur butterfly, sulfur butterfly",
"lycaenid, lycaenid butterfly",
"starfish, sea star",
"sea urchin",
"sea cucumber, holothurian",
"wood rabbit, cottontail, cottontail rabbit",
"hare",
"Angora, Angora rabbit",
"hamster",
"porcupine, hedgehog",
"fox squirrel, eastern fox squirrel, Sciurus niger",
"marmot",
"beaver",
"guinea pig, Cavia cobaya",
"sorrel",
"zebra",
"hog, pig, grunter, squealer, Sus scrofa",
"wild boar, boar, Sus scrofa",
"warthog",
"hippopotamus, hippo, river horse, Hippopotamus amphibius",
"ox",
"water buffalo, water ox, Asiatic buffalo, Bubalus bubalis",
"bison",
"ram, tup",
"bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis",
"ibex, Capra ibex",
"hartebeest",
"impala, Aepyceros melampus",
"gazelle",
"Arabian camel, dromedary, Camelus dromedarius",
"llama",
"weasel",
"mink",
"polecat, fitch, foulmart, foumart, Mustela putorius",
"black-footed ferret, ferret, Mustela nigripes",
"otter",
"skunk, polecat, wood pussy",
"badger",
"armadillo",
"three-toed sloth, ai, Bradypus tridactylus",
"orangutan, orang, orangutang, Pongo pygmaeus",
"gorilla, Gorilla gorilla",
"chimpanzee, chimp, Pan troglodytes",
"gibbon, Hylobates lar",
"siamang, Hylobates syndactylus, Symphalangus syndactylus",
"guenon, guenon monkey",
"patas, hussar monkey, Erythrocebus patas",
"baboon",
"macaque",
"langur",
"colobus, colobus monkey",
"proboscis monkey, Nasalis larvatus",
"marmoset",
"capuchin, ringtail, Cebus capucinus",
"howler monkey, howler",
"titi, titi monkey",
"spider monkey, Ateles geoffroyi",
"squirrel monkey, Saimiri sciureus",
"Madagascar cat, ring-tailed lemur, Lemur catta",
"indri, indris, Indri indri, Indri brevicaudatus",
"Indian elephant, Elephas maximus",
"African elephant, Loxodonta africana",
"lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens",
"giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca",
"barracouta, snoek",
"eel",
"coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch",
"rock beauty, Holocanthus tricolor",
"anemone fish",
"sturgeon",
"gar, garfish, garpike, billfish, Lepisosteus osseus",
"lionfish",
"puffer, pufferfish, blowfish, globefish",
"abacus",
"abaya",
"academic gown, academic robe, judge's robe",
"accordion, piano accordion, squeeze box",
"acoustic guitar",
"aircraft carrier, carrier, flattop, attack aircraft carrier",
"airliner",
"airship, dirigible",
"altar",
"ambulance",
"amphibian, amphibious vehicle",
"analog clock",
"apiary, bee house",
"apron",
"ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin",
"assault rifle, assault gun",
"backpack, back pack, knapsack, packsack, rucksack, haversack",
"bakery, bakeshop, bakehouse",
"balance beam, beam",
"balloon",
"ballpoint, ballpoint pen, ballpen, Biro",
"Band Aid",
"banjo",
"bannister, banister, balustrade, balusters, handrail",
"barbell",
"barber chair",
"barbershop",
"barn",
"barometer",
"barrel, cask",
"barrow, garden cart, lawn cart, wheelbarrow",
"baseball",
"basketball",
"bassinet",
"bassoon",
"bathing cap, swimming cap",
"bath towel",
"bathtub, bathing tub, bath, tub",
"beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon",
"beacon, lighthouse, beacon light, pharos",
"beaker",
"bearskin, busby, shako",
"beer bottle",
"beer glass",
"bell cote, bell cot",
"bib",
"bicycle-built-for-two, tandem bicycle, tandem",
"bikini, two-piece",
"binder, ring-binder",
"binoculars, field glasses, opera glasses",
"birdhouse",
"boathouse",
"bobsled, bobsleigh, bob",
"bolo tie, bolo, bola tie, bola",
"bonnet, poke bonnet",
"bookcase",
"bookshop, bookstore, bookstall",
"bottlecap",
"bow",
"bow tie, bow-tie, bowtie",
"brass, memorial tablet, plaque",
"brassiere, bra, bandeau",
"breakwater, groin, groyne, mole, bulwark, seawall, jetty",
"breastplate, aegis, egis",
"broom",
"bucket, pail",
"buckle",
"bulletproof vest",
"bullet train, bullet",
"butcher shop, meat market",
"cab, hack, taxi, taxicab",
"caldron, cauldron",
"candle, taper, wax light",
"cannon",
"canoe",
"can opener, tin opener",
"cardigan",
"car mirror",
"carousel, carrousel, merry-go-round, roundabout, whirligig",
"carpenter's kit, tool kit",
"carton",
"car wheel",
"cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM",
"cassette",
"cassette player",
"castle",
"catamaran",
"CD player",
"cello, violoncello",
"cellular telephone, cellular phone, cellphone, cell, mobile phone",
"chain",
"chainlink fence",
"chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour",
"chain saw, chainsaw",
"chest",
"chiffonier, commode",
"chime, bell, gong",
"china cabinet, china closet",
"Christmas stocking",
"church, church building",
"cinema, movie theater, movie theatre, movie house, picture palace",
"cleaver, meat cleaver, chopper",
"cliff dwelling",
"cloak",
"clog, geta, patten, sabot",
"cocktail shaker",
"coffee mug",
"coffeepot",
"coil, spiral, volute, whorl, helix",
"combination lock",
"computer keyboard, keypad",
"confectionery, confectionary, candy store",
"container ship, containership, container vessel",
"convertible",
"corkscrew, bottle screw",
"cornet, horn, trumpet, trump",
"cowboy boot",
"cowboy hat, ten-gallon hat",
"cradle",
"crane",
"crash helmet",
"crate",
"crib, cot",
"Crock Pot",
"croquet ball",
"crutch",
"cuirass",
"dam, dike, dyke",
"desk",
"desktop computer",
"dial telephone, dial phone",
"diaper, nappy, napkin",
"digital clock",
"digital watch",
"dining table, board",
"dishrag, dishcloth",
"dishwasher, dish washer, dishwashing machine",
"disk brake, disc brake",
"dock, dockage, docking facility",
"dogsled, dog sled, dog sleigh",
"dome",
"doormat, welcome mat",
"drilling platform, offshore rig",
"drum, membranophone, tympan",
"drumstick",
"dumbbell",
"Dutch oven",
"electric fan, blower",
"electric guitar",
"electric locomotive",
"entertainment center",
"envelope",
"espresso maker",
"face powder",
"feather boa, boa",
"file, file cabinet, filing cabinet",
"fireboat",
"fire engine, fire truck",
"fire screen, fireguard",
"flagpole, flagstaff",
"flute, transverse flute",
"folding chair",
"football helmet",
"forklift",
"fountain",
"fountain pen",
"four-poster",
"freight car",
"French horn, horn",
"frying pan, frypan, skillet",
"fur coat",
"garbage truck, dustcart",
"gasmask, respirator, gas helmet",
"gas pump, gasoline pump, petrol pump, island dispenser",
"goblet",
"go-kart",
"golf ball",
"golfcart, golf cart",
"gondola",
"gong, tam-tam",
"gown",
"grand piano, grand",
"greenhouse, nursery, glasshouse",
"grille, radiator grille",
"grocery store, grocery, food market, market",
"guillotine",
"hair slide",
"hair spray",
"half track",
"hammer",
"hamper",
"hand blower, blow dryer, blow drier, hair dryer, hair drier",
"hand-held computer, hand-held microcomputer",
"handkerchief, hankie, hanky, hankey",
"hard disc, hard disk, fixed disk",
"harmonica, mouth organ, harp, mouth harp",
"harp",
"harvester, reaper",
"hatchet",
"holster",
"home theater, home theatre",
"honeycomb",
"hook, claw",
"hoopskirt, crinoline",
"horizontal bar, high bar",
"horse cart, horse-cart",
"hourglass",
"iPod",
"iron, smoothing iron",
"jack-o'-lantern",
"jean, blue jean, denim",
"jeep, landrover",
"jersey, T-shirt, tee shirt",
"jigsaw puzzle",
"jinrikisha, ricksha, rickshaw",
"joystick",
"kimono",
"knee pad",
"knot",
"lab coat, laboratory coat",
"ladle",
"lampshade, lamp shade",
"laptop, laptop computer",
"lawn mower, mower",
"lens cap, lens cover",
"letter opener, paper knife, paperknife",
"library",
"lifeboat",
"lighter, light, igniter, ignitor",
"limousine, limo",
"liner, ocean liner",
"lipstick, lip rouge",
"Loafer",
"lotion",
"loudspeaker, speaker, speaker unit, loudspeaker system, speaker system",
"loupe, jeweler's loupe",
"lumbermill, sawmill",
"magnetic compass",
"mailbag, postbag",
"mailbox, letter box",
"maillot",
"maillot, tank suit",
"manhole cover",
"maraca",
"marimba, xylophone",
"mask",
"matchstick",
"maypole",
"maze, labyrinth",
"measuring cup",
"medicine chest, medicine cabinet",
"megalith, megalithic structure",
"microphone, mike",
"microwave, microwave oven",
"military uniform",
"milk can",
"minibus",
"miniskirt, mini",
"minivan",
"missile",
"mitten",
"mixing bowl",
"mobile home, manufactured home",
"Model T",
"modem",
"monastery",
"monitor",
"moped",
"mortar",
"mortarboard",
"mosque",
"mosquito net",
"motor scooter, scooter",
"mountain bike, all-terrain bike, off-roader",
"mountain tent",
"mouse, computer mouse",
"mousetrap",
"moving van",
"muzzle",
"nail",
"neck brace",
"necklace",
"nipple",
"notebook, notebook computer",
"obelisk",
"oboe, hautboy, hautbois",
"ocarina, sweet potato",
"odometer, hodometer, mileometer, milometer",
"oil filter",
"organ, pipe organ",
"oscilloscope, scope, cathode-ray oscilloscope, CRO",
"overskirt",
"oxcart",
"oxygen mask",
"packet",
"paddle, boat paddle",
"paddlewheel, paddle wheel",
"padlock",
"paintbrush",
"pajama, pyjama, pj's, jammies",
"palace",
"panpipe, pandean pipe, syrinx",
"paper towel",
"parachute, chute",
"parallel bars, bars",
"park bench",
"parking meter",
"passenger car, coach, carriage",
"patio, terrace",
"pay-phone, pay-station",
"pedestal, plinth, footstall",
"pencil box, pencil case",
"pencil sharpener",
"perfume, essence",
"Petri dish",
"photocopier",
"pick, plectrum, plectron",
"pickelhaube",
"picket fence, paling",
"pickup, pickup truck",
"pier",
"piggy bank, penny bank",
"pill bottle",
"pillow",
"ping-pong ball",
"pinwheel",
"pirate, pirate ship",
"pitcher, ewer",
"plane, carpenter's plane, woodworking plane",
"planetarium",
"plastic bag",
"plate rack",
"plow, plough",
"plunger, plumber's helper",
"Polaroid camera, Polaroid Land camera",
"pole",
"police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria",
"poncho",
"pool table, billiard table, snooker table",
"pop bottle, soda bottle",
"pot, flowerpot",
"potter's wheel",
"power drill",
"prayer rug, prayer mat",
"printer",
"prison, prison house",
"projectile, missile",
"projector",
"puck, hockey puck",
"punching bag, punch bag, punching ball, punchball",
"purse",
"quill, quill pen",
"quilt, comforter, comfort, puff",
"racer, race car, racing car",
"racket, racquet",
"radiator",
"radio, wireless",
"radio telescope, radio reflector",
"rain barrel",
"recreational vehicle, RV, R.V.",
"reel",
"reflex camera",
"refrigerator, icebox",
"remote control, remote",
"restaurant, eating house, eating place, eatery",
"revolver, six-gun, six-shooter",
"rifle",
"rocking chair, rocker",
"rotisserie",
"rubber eraser, rubber, pencil eraser",
"rugby ball",
"rule, ruler",
"running shoe",
"safe",
"safety pin",
"saltshaker, salt shaker",
"sandal",
"sarong",
"sax, saxophone",
"scabbard",
"scale, weighing machine",
"school bus",
"schooner",
"scoreboard",
"screen, CRT screen",
"screw",
"screwdriver",
"seat belt, seatbelt",
"sewing machine",
"shield, buckler",
"shoe shop, shoe-shop, shoe store",
"shoji",
"shopping basket",
"shopping cart",
"shovel",
"shower cap",
"shower curtain",
"ski",
"ski mask",
"sleeping bag",
"slide rule, slipstick",
"sliding door",
"slot, one-armed bandit",
"snorkel",
"snowmobile",
"snowplow, snowplough",
"soap dispenser",
"soccer ball",
"sock",
"solar dish, solar collector, solar furnace",
"sombrero",
"soup bowl",
"space bar",
"space heater",
"space shuttle",
"spatula",
"speedboat",
"spider web, spider's web",
"spindle",
"sports car, sport car",
"spotlight, spot",
"stage",
"steam locomotive",
"steel arch bridge",
"steel drum",
"stethoscope",
"stole",
"stone wall",
"stopwatch, stop watch",
"stove",
"strainer",
"streetcar, tram, tramcar, trolley, trolley car",
"stretcher",
"studio couch, day bed",
"stupa, tope",
"submarine, pigboat, sub, U-boat",
"suit, suit of clothes",
"sundial",
"sunglass",
"sunglasses, dark glasses, shades",
"sunscreen, sunblock, sun blocker",
"suspension bridge",
"swab, swob, mop",
"sweatshirt",
"swimming trunks, bathing trunks",
"swing",
"switch, electric switch, electrical switch",
"syringe",
"table lamp",
"tank, army tank, armored combat vehicle, armoured combat vehicle",
"tape player",
"teapot",
"teddy, teddy bear",
"television, television system",
"tennis ball",
"thatch, thatched roof",
"theater curtain, theatre curtain",
"thimble",
"thresher, thrasher, threshing machine",
"throne",
"tile roof",
"toaster",
"tobacco shop, tobacconist shop, tobacconist",
"toilet seat",
"torch",
"totem pole",
"tow truck, tow car, wrecker",
"toyshop",
"tractor",
"trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi",
"tray",
"trench coat",
"tricycle, trike, velocipede",
"trimaran",
"tripod",
"triumphal arch",
"trolleybus, trolley coach, trackless trolley",
"trombone",
"tub, vat",
"turnstile",
"typewriter keyboard",
"umbrella",
"unicycle, monocycle",
"upright, upright piano",
"vacuum, vacuum cleaner",
"vase",
"vault",
"velvet",
"vending machine",
"vestment",
"viaduct",
"violin, fiddle",
"volleyball",
"waffle iron",
"wall clock",
"wallet, billfold, notecase, pocketbook",
"wardrobe, closet, press",
"warplane, military plane",
"washbasin, handbasin, washbowl, lavabo, wash-hand basin",
"washer, automatic washer, washing machine",
"water bottle",
"water jug",
"water tower",
"whiskey jug",
"whistle",
"wig",
"window screen",
"window shade",
"Windsor tie",
"wine bottle",
"wing",
"wok",
"wooden spoon",
"wool, woolen, woollen",
"worm fence, snake fence, snake-rail fence, Virginia fence",
"wreck",
"yawl",
"yurt",
"web site, website, internet site, site",
"comic book",
"crossword puzzle, crossword",
"street sign",
"traffic light, traffic signal, stoplight",
"book jacket, dust cover, dust jacket, dust wrapper",
"menu",
"plate",
"guacamole",
"consomme",
"hot pot, hotpot",
"trifle",
"ice cream, icecream",
"ice lolly, lolly, lollipop, popsicle",
"French loaf",
"bagel, beigel",
"pretzel",
"cheeseburger",
"hotdog, hot dog, red hot",
"mashed potato",
"head cabbage",
"broccoli",
"cauliflower",
"zucchini, courgette",
"spaghetti squash",
"acorn squash",
"butternut squash",
"cucumber, cuke",
"artichoke, globe artichoke",
"bell pepper",
"cardoon",
"mushroom",
"Granny Smith",
"strawberry",
"orange",
"lemon",
"fig",
"pineapple, ananas",
"banana",
"jackfruit, jak, jack",
"custard apple",
"pomegranate",
"hay",
"carbonara",
"chocolate sauce, chocolate syrup",
"dough",
"meat loaf, meatloaf",
"pizza, pizza pie",
"potpie",
"burrito",
"red wine",
"espresso",
"cup",
"eggnog",
"alp",
"bubble",
"cliff, drop, drop-off",
"coral reef",
"geyser",
"lakeside, lakeshore",
"promontory, headland, head, foreland",
"sandbar, sand bar",
"seashore, coast, seacoast, sea-coast",
"valley, vale",
"volcano",
"ballplayer, baseball player",
"groom, bridegroom",
"scuba diver",
"rapeseed",
"daisy",
"yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum",
"corn",
"acorn",
"hip, rose hip, rosehip",
"buckeye, horse chestnut, conker",
"coral fungus",
"agaric",
"gyromitra",
"stinkhorn, carrion fungus",
"earthstar",
"hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa",
"bolete",
"ear, spike, capitulum",
"toilet tissue, toilet paper, bathroom tissue"
};
//类别转换对应声明
//examle：0 "动物"
//...
int trans[] = {
        //example:
        // 0,0,0,0,0,0,0,0,0,0,
        // 0,0,0,0,0,0,1,1,1,1,
        //...
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1
};
const char * imagenet_classes_chinese[] = {
"鲤鱼, 欧洲丁鱥",
"金鱼, 鲫鱼",
"大白鲨, 食人鲨, 食人鲛",
"虎鲨, 鼬鲛",
"锤头, 双髻鲨",
"电鳐,  电鱼, 电鳗",
"黄貂鱼",
"公鸡",
"母鸡",
"鸵鸟",
"燕雀, 花雀",
"金翅雀, 红额金翅雀",
"家朱雀, 红雀",
"灯芯草雀, 雪鸟",
"靛蓝彩鹀, 靛蓝雀",
"知更鸟, 美洲知更鸟",
"夜莺",
"松鸡",
"喜鹊",
"山雀",
"河鸟",
"风筝",
"秃鹰, 北美秃鹰, 白头鹰",
"秃鹫",
"乌林鸮, 大灰猫头鹰",
"欧洲火蜥蜴, 火蝾螈",
"普通蝾螈",
"水蜥",
"斑点钝口螈, 美西螈",
"墨西哥钝口螈, 泥狗, 大钝口螈",
" 牛蛙",
"树蛙",
"尾蟾, 钟蟾, 有棱纹的蟾蜍",
"红海龟, 赤蠵龟, 蠵龟",
"棱皮龟, 革龟",
"淡水龟",
"水龟",
"箱龟",
"横纹鞘爪虎",
"常见的鬣蜥, 大蜥蜴",
"绿安乐蜥, 变色龙",
"长尾鳕, 鞭尾蜥蜴",
"飞龙科蜥蜴",
"伞蜥, 斗篷蜥属",
"鳄蜥",
"毒蜥, 钝尾毒蜥",
"绿蜥蜴, 蝎虎星座冬青",
"非洲变色龙, 地中海变色龙",
"科摩多龙, 科莫多蜥蜴, 龙蜥蜴, 大蜥蜴",
"尼罗鳄",
"美国短吻鳄,密西西比鳄",
"三角恐龙",
"雷蛇, 蠕蛇",
"环颈蛇",
"猪鼻蛇, 吹气蝰, 沙蝰",
"青蛇, 青草蛇",
"王蛇, 蛇王",
"花纹蛇",
"水蛇",
"藤蛇",
"夜蛇",
"蟒蛇, 红尾蚺",
"岩蟒, 岩蛇, 非洲岩蟒",
"印度眼镜蛇",
"绿曼巴",
"海蛇",
"角蝰, 沙蝰",
"响尾蛇, 菱背响尾蛇",
"响尾蛇, 角响尾蛇",
"三叶虫",
"盲蜘蛛",
"蝎子",
"黑色和金色的花园蜘蛛",
"谷仓的蜘蛛",
"十字园蛛",
"黑寡妇, 黑寡妇蜘蛛",
"塔兰图拉毒蛛",
"狼蛛, 掠食蛛",
"蜱",
"蜈蚣",
"黑琴鸡",
"雷鸟",
"披肩鸡, 鹧鸪",
"北美草原松鸡, 野鸡",
"孔雀",
"鹌鹑",
"石鸡",
"非洲灰鹦鹉",
"金刚鹦鹉",
"葵花凤头鹦鹉",
"吸蜜鹦鹉",
"番鹃",
"蜂虎",
"犀鸟",
"蜂鸟",
"食虫鸟",
"巨嘴鸟",
"公鸭",
"红胸秋沙鸭",
"鹅",
"黑天鹅",
"长牙象",
"针鼹, 食蚁兽",
"鸭嘴兽",
"小袋鼠, 刷袋鼠",
"树袋熊, 袋鼠熊, 无尾熊",
"袋熊",
"水母",
"海葵, 银莲花",
"脑珊瑚",
"扁虫, 扁蠕虫",
"线虫, 蛔虫",
"贝壳",
"蜗牛",
"鼻涕虫",
"海参, 裸鳃类",
"石鳖, 甲胄壳",
"鹦鹉螺",
"珍宝蟹, 首长黄道蟹",
"岩蟹, 斑纹黄道蟹",
"招潮蟹",
"皇帝蟹, 阿拉斯加蟹, 阿拉斯加帝王蟹, 堪察加拟石蟹",
"美洲螯龙虾, 缅因大龙虾",
"龙虾, 小龙虾, 海小龙虾",
"小龙虾, 喇蛄, 龙虾王",
"寄生蟹",
"等足类动物",
"白鹳",
"黑鹳",
"篦鹭",
"火烈鸟",
"小蓝鹭",
"美国白鹭, 大白鹭",
"麻鸦",
"鹤",
"涉禽",
"欧洲黑水鸡, 紫水鸡",
"美洲白冠鸡, 马什母鸡, 泥鸡, 水鸡, 美洲骨顶",
"大鸨",
"翻石鹬",
"红背鹬, 黑腹滨鹬",
"红脚鹬",
"长嘴半蹼鹬",
"蛎鹬",
"鹈鹕",
"国王企鹅",
"信天翁",
"灰鲸, 章鱼, 白鳍豚",
"虎鲸, 逆戟鲸, 公鲸, 海狼",
"儒艮",
"海狮",
"吉娃娃",
"日本猎犬",
"马耳他狗",
"小狮子狗, 北京哈叭狗",
"狮子狗",
"布伦海姆狗",
"蝶耳狗",
"玩具狗",
"罗得西亚脊背犬",
"阿富汗猎犬",
"巴塞特猎犬",
"小猎犬",
"寻血猎犬, 警犬",
"蓝色快狗",
"黑褐猎浣熊犬",
"沃克猎犬, 沃克猎狐犬",
"英国猎狐犬",
"美洲赤狗",
"波尔瑞, 俄国狼犬",
"爱尔兰猎狼犬",
"意大利灵缇犬",
"惠比特犬, 小灵犬",
"依比沙猎犬, 伊维萨猎犬",
"挪威猎鹿犬, 猎鹿犬",
"奥达猎犬,水獭猎犬",
"萨卢基狗,瞪羚猎犬",
"苏格兰猎鹿犬, 猎鹿犬",
"魏玛猎狗",
"斯塔福德郡斗牛梗",
"美国斯塔福德梗, 斯塔福德梗, 美国比特犬, 比特犬",
"贝得灵顿厚毛犬",
"博德猎狐犬",
"凯利蓝梗",
"爱尔兰梗",
"诺福克梗",
"诺里奇梗犬",
"约克郡犬",
"苏格兰铁利亚",
"湖畔梗",
"西里汉梗,西里汉",
"艾尔谷犬, 万能梗",
"凯恩,凯恩梗",
"澳洲梗",
"英国小猎犬, 短脚狄文挭狗, 丹迪丁蒙梗狗, 短脚长身梗狗",
"波士顿公牛, 波士顿梗",
"迷你雪纳瑞",
"巨型雪纳瑞犬",
"标准型雪纳瑞犬",
"苏格兰梗",
"西藏梗, 菊花犬",
"丝毛狗, 悉尼丝毛梗",
"爱尔兰软毛挭",
"西部高地白挭",
"拉萨,拉萨阿普索犬",
"平滑毛寻回犬",
"卷毛寻回犬",
"金毛猎犬",
"拉布拉多寻回犬",
"乞沙比克猎犬, 切萨皮克海湾寻回犬",
"德国短毛",
"维希拉猎犬, 匈牙利的指针",
"英国赛特犬",
"爱尔兰猎犬, 红猎犬",
"哥顿塞特犬",
"布列塔尼猎犬",
"矮脚长耳猎犬,黄毛猎犬",
"史宾格犬, 英国激飞猎犬",
"威尔斯激飞猎犬",
"可卡犬, 英国可卡犬",
"萨西克斯郡猎犬",
"爱尔兰水猎犬",
"白警犬, 哥威斯犬",
"比利时种小狗",
"比利时牧羊狗",
"玛伦牧羊犬",
"伯瑞犬, 布里牧羊犬",
"澳大利亚护羊犬",
"匈牙利种牧羊犬",
"古英国牧羊犬, 短尾",
"设得兰牧羊犬",
"柯利牧羊狗",
"博德牧羊犬",
"法兰德斯牧牛狗",
"罗特韦尔犬",
"德国牧羊犬, 阿尔萨斯狼犬, 德国警犬",
"杜宾犬",
"迷你笃宾犬",
"大瑞士山地犬",
"伯尔尼兹山地犬",
"阿彭策勒",
"恩特雷布赫山犬",
"拳师犬",
"牛头獒",
"藏獒, 西藏獒犬",
"法国斗牛犬",
"大丹狗",
"圣伯纳德狗, 瑞士救护犬",
"爱斯基摩狗, 哈士奇",
"马拉缪, 阿拉斯加雪橇狗",
"哈士奇, 西伯利亚哈士奇",
"大麦町犬, 达尔马提亚犬",
"艾芬笃宾犬, 艾芬品, 猴头梗",
"巴辛吉犬",
" 哈巴狗, 狮子狗",
"莱翁贝格",
"纽芬兰犬",
"大白熊犬",
"萨莫耶德犬",
"博美犬",
"松狮犬, 中国黑鼻狗, 中国松狮犬",
"荷兰卷尾狮毛狗",
"布鲁塞尔格林芬犬",
"彭布罗克, 彭布洛克威尔士科基犬",
"羊毛衫, 卡迪根威尔士柯基犬",
"玩具贵宾犬",
"迷你贵宾犬",
"标准贵宾犬",
"墨西哥无毛狗",
"大灰狼, 苍狼, 狼",
"白狼, 北极狼, 阿拉斯加苔原狼",
"红狼, 鬃狼",
"郊狼, 北美草原狼",
"澳洲野狗, 澳大利亚野犬",
"豺, 印度野犬, 亚洲豺犬",
"非洲猎犬, 非洲野犬",
"鬣狗, 土狼",
"红狐狸, 赤狐, 银狐",
"墨西哥狐, 敏狐, 小狐",
"北极狐, 白狐",
"灰狐",
"斑猫, 虎斑猫",
"山猫, 虎猫",
"波斯猫",
"暹罗猫",
"埃及猫",
"美洲狮, 美洲豹, 美洲金猫属, 山猫, 山地狮,  黑豹",
"猞猁, 山猫, 美洲豹",
"豹, 美洲豹, 金钱豹",
"雪豹",
"美洲虎, 黑豹, 美洲豹",
"狮子, 百兽之王, 非洲狮",
"老虎, 孟加拉虎",
"猎豹, 印度豹",
"棕熊, 熊先生",
"美洲黑熊, 黑熊",
"冰熊, 北极熊",
"印度懒熊, 懒熊",
"猫鼬, 獴狐猴",
"猫鼬, 海猫",
"虎甲",
"瓢虫",
"土鳖虫, 步甲",
"天牛",
"叶甲, 金花虫科",
"蜣螂, 金龟子科, 甲虫",
"兜虫亚科, 独角仙, 犀甲虫",
"象鼻虫",
"苍蝇",
"蜜蜂",
"蚂蚁",
"蚱蜢, 跳虫",
"蟋蟀",
"竹节虫",
"蟑螂",
"螳螂",
"蝉",
"叶蝉",
"草蜻蛉, 草蛉",
"蜻蜓, 蚊子鹰, 斯基特鹰",
"豆娘（一种蜻蜓）",
"海军上将",
"小圈, 长卷发, 眼蝶族",
"君主斑蝶, 黑脉金斑蝶, 斑蝶亚科",
"纹白蝶",
"白蝴蝶, 黄蝶",
"灰蝶科",
"海星, 海马",
"海胆",
"海参",
"白尾灰兔, 棉尾兔属",
"野兔",
"安哥拉, 安哥拉兔",
"仓鼠",
"箭猪, 豪猪, 刺猬",
"黑松鼠, 狐松鼠",
"土拨鼠, 旱獭",
"河狸, 海狸",
"豚鼠, 天竺鼠, 荷兰猪",
"栗色毛的动物",
"斑马",
"猪, 野猪",
"野猪, （未阉的）公猪",
"疣猪（一种非洲野猪）",
"河马",
"牛, 公牛",
"水牛, 亚洲水牛, 印度水牛",
"北美野牛, 欧洲野牛",
"公羊",
"大角羊, 落基山大角羊, 加拿大盘羊",
"野生山羊, 羱羊",
"大羚羊",
"黑斑羚, 高角羚",
"瞪羚；小羚羊",
"阿拉伯单峰驼, 单峰骆驼",
"美洲驼, 无峰驼",
"鼬鼠, 黄鼠狼",
"貂",
"北美产之臭鼬类, 艾鼬（欧洲产）, 鸡貂, 臭猫, 欧洲雪貂",
"黑足鼬, 蒙眼貂, 雪貂, 白鼬",
"水獭",
"臭鼬, 黄鼠狼",
"獾",
"犰狳",
"树懒属, 三趾树懒",
"猩猩",
"大猩猩",
"黑猩猩",
"长臂猿",
"合趾猴, 大长臂猿",
"长尾猴",
"赤猴",
"狒狒",
"猕猴",
"叶猴",
"疣猴, 髯猴（产于非洲）",
"长鼻猴",
"狨猴, 小猿",
"卷尾猴, 僧帽猴, 浣熊, 圈尾猫",
"吼猴",
"伶猴",
"蜘蛛猿",
"松鼠猴",
"节尾狐猴, 环尾狐猴",
"马达加斯加大狐猴",
"印度象, 亚洲象",
"非洲象",
"小熊猫, 熊猫",
"大熊猫",
"帆蜥鱼, 杖鱼",
"鳗鱼, 鳝鱼",
"银大马哈鱼",
"石美人",
"双锯鱼, 海葵鱼, 小丑鱼",
"鲟鱼",
"雀鳝, 颌针鱼, 长嘴硬鳞鱼, 长吻雀鳝",
"狮子鱼",
"河豚",
"算盘",
"长袍",
"学位袍, 学术袍, 法官袍",
"手风琴, 键盘式手风琴",
"原声吉他, 木吉他",
"航空母舰",
"班机, 大型客机",
"飞艇, 飞船",
"祭坛",
"救护车",
"两栖动物, 两栖车辆",
"模拟时钟, 指针式类比时钟",
"养蜂场, 蜂房",
"围裙",
"垃圾桶",
"突击步枪",
"背包",
"面包店",
"平衡梁, 梁",
"气球",
"圆珠笔",
"创口贴",
"班卓琴, 五弦琴",
"栏杆",
"杠铃",
"理发椅",
"理发店",
"谷仓, 畜棚, 车库",
"气压计, 晴雨表",
"桶",
"手推车, 花园手推车, 草坪手推车",
"棒球",
"篮球",
"摇篮",
"低音管",
"浴帽, 泳帽",
"浴巾",
"浴缸",
"沙滩车, 旅行车",
"灯塔",
"烧杯, 大口杯",
"熊皮衣, 毛皮制高帽子, （顶有羽毛饰物的）有檐平顶筒状军帽",
"啤酒瓶",
"啤酒杯",
"钟状小屋",
"龙头, 围嘴",
"双人自行车",
"两件套比基尼",
"活页夹",
"双筒望远镜, 野外望远镜, 望远镜",
"禽舍, 小鸟舍",
"船库, 艇库",
"雪橇",
"饰扣式领带",
"阀盖",
"书柜",
"书店, 书报摊",
"纸瓶盖",
"蝴蝶结",
"领结",
"黄铜, 纪念版, 牌匾",
"胸罩",
"防波堤",
"护胸甲",
"扫帚",
"桶",
"皮带扣",
"防弹背心, 避弹衣",
"动车, 子弹",
"肉店",
"出租车",
"大锅",
"蜡烛",
"大炮",
"独木舟, 轻舟",
"开罐器",
"羊毛衫, 开襟羊毛衫",
"后视镜",
"旋转木马",
"工具箱",
"纸板箱",
"车轮",
"自动提款机, 自动柜员机",
"盒式磁带",
"录音带放音机, 卡式录音机",
"城堡",
"双体船, 长筏, 游艇",
"激光唱机, CD播放器",
"大提琴",
"手机",
"链, 枷锁",
"链状栅栏",
"链甲",
"链锯,电锯",
"胸部, 衣柜, 箱子, 金库",
"书柜, 衣柜",
"铃, 钟, 锣",
"瓷器柜",
"圣诞袜",
"教堂",
"电影院",
"切肉刀, 菜刀",
"悬崖住所",
"斗篷, 披风",
"木屐",
"调酒器, 鸡尾酒调制器",
"咖啡杯",
"咖啡壶",
"线圈, 螺旋, 蜗壳, 螺纹",
"密码锁",
"电脑键盘, 键盘",
"糖果店",
"集装箱船",
"敞篷车",
"开塞钻, 开瓶器, 螺旋起重机, 螺旋拔塞机",
"小号, 喇叭",
"牛仔靴",
"牛仔帽",
"摇篮",
"鹤",
"安全帽, 头盔",
"板条箱",
"婴儿床, 床",
"慢炖锅",
"槌球",
"拐杖",
"护胸甲",
"大坝",
"书桌",
"台式电脑",
"转盘电话机, 拨号式电话机",
"尿布",
"数字显示式时钟",
"数字显示式电子表",
"餐桌",
"抹布",
"洗碗机",
"盘式制动器",
"码头",
"狗拉雪橇",
"穹丘, 圆屋顶",
"门口擦鞋垫",
"钻井平台, 海上钻机",
"鼓, 膜鸣乐器, 鼓膜, 鼓室",
"鸡腿, 鼓槌",
"哑铃",
"荷兰灶",
"电动风扇, 鼓风机",
"电吉他",
"电力机车",
"娱乐中心, 娱乐城, 电视",
"信封",
"咖啡机",
"面粉, 散粉",
"羽毛披肩, 女用长围巾",
"文件柜",
"消防船",
"消防车",
"防火墙",
"旗杆",
"长笛, 横笛",
"折叠椅",
"橄榄球头盔",
"铲车, 堆高机",
"喷泉",
"钢笔",
"有四根帷柱的床",
"货车",
"法国号, 喇叭, 号角",
"煎锅",
"皮毛大衣",
"垃圾车",
"防毒面具, 呼吸器, 防毒头盔",
"汽油泵",
"酒杯, 高脚杯",
"卡丁车",
"高尔夫球",
"高尔夫球车",
"两头尖的平底船",
"锣, 铜锣",
"长袍, 礼服, 长外衣",
"三角钢琴, 大钢琴",
"温室",
"格栅, 散热器格栅",
"杂货店",
"断头台",
"小发夹",
"发胶",
"半履带车",
"铁锤, 链球",
"食盒, 食篮",
"吹风机",
"手持电脑",
"手帕",
"硬盘",
"口琴, 竖琴, 口簧",
"竖琴",
"收割机",
"短柄斧",
"手枪皮套",
"家庭影院",
"蜂巢",
"钩, 爪",
"裙子, 裙衬",
"高杠, 单杠",
"马车",
"沙漏, 水漏",
"iPod（苹果公司音乐播放器）",
"熨斗",
"杰克南瓜灯",
"牛仔布, 蓝色牛仔布",
"吉普车,路虎",
"运动衫, t恤",
"拼图, 七巧板",
"黄包车, 人力车",
"控制杆, 操纵杆",
"和服",
"护膝",
"结, 节瘤, 疙瘩",
"实验服",
"长柄勺, 铁水包",
"灯罩",
"笔记本电脑",
"割草机",
"镜头盖",
"开信刀, 纸刀",
"图书馆, 藏书室",
"救生艇",
"点火器",
"豪华轿车",
"班轮, 远洋班轮",
"口红",
"乐福鞋, 包子鞋, 拖鞋",
"洗液, 洗涤剂",
"扬声器",
"放大镜",
"锯木厂",
"磁罗盘",
"邮袋, 邮差背包",
"邮箱, 信箱",
"紧身衣",
"女游泳衣, 有肩带浴衣",
"井盖",
"沙球",
"马林巴琴, 木琴",
"面具, 口罩",
"火柴棍, 火柴杆",
"五朔节花柱",
"迷宫",
"量杯",
"医药箱",
"巨石, 巨石结构",
"麦克风",
"微波炉",
"军装",
"牛奶罐",
"公共小型巴士",
"超短裙, 迷你裙",
"多功能休旅车",
"导弹",
"连指手套",
"搅拌钵",
"活动房层, 拖车住房",
"T型发动机小汽车",
"调制解调器",
"修道院, 僧侣",
"监视器",
"助动车, 机动脚踏两用车",
"迫击炮",
"学位帽, 灰泥板",
"清真寺",
"蚊帐",
"小型摩托车, 摩托车",
"山地车, 全地形车, 越野车",
"登山帐篷",
"鼠标, 电脑鼠标",
"捕鼠器, 老鼠夹",
"搬家汽车",
"枪口, 炮口",
"指甲, 钉子",
"颈托",
"项链",
"乳头, 奶头, 奶嘴",
"笔记本, 笔记本电脑",
"方尖碑, 方尖塔",
"双簧管, 高音双簧箫",
"陶笛, 红薯",
"里程计",
"滤油器",
"管风琴",
"示波器",
"罩裙, 半裙",
"牛车",
"氧气面罩",
"信息包, 小包",
"桨",
"明轮, 桨轮",
"挂锁",
"画笔, 漆刷",
"睡衣",
"宫殿",
"排笛, 牧羊神之笛, 潘神销",
"纸巾",
"降落伞",
"双杠",
"公园长椅",
"停车记时器",
"客车, 长途公车, 四轮大马车",
"露台",
"公共电话, 公用电话亭",
"基座",
"铅笔盒",
"卷笔刀",
"香水, 香精",
"培养皿",
"影印机, 复印机",
"鹤嘴锄, 拨子, 琴拨",
"尖顶盔",
"栅栏",
"小卡车, 敞蓬小型载货卡车",
"码头, 直码头, 桥墩",
"储蓄罐",
"药瓶子",
"枕头",
"乒乓球",
"纸风车",
"海盗船",
"大口水壶, 大水罐",
"刨子, 木工刨",
"天文馆, 行星仪",
"塑料袋",
"餐具架",
"犁",
"活塞",
"拍立得相机",
"杆",
"警车, 囚车",
"雨披, 斗篷",
"台球桌",
"汽水瓶",
"花盆",
"陶工旋盘",
"机械钻, 动力钻机",
"跪垫, 礼拜毯",
"打印机",
"监狱",
"射弹, 导弹",
"投影仪",
"冰球",
"拳击袋, 拳击球",
"钱包, 手提包",
"羽毛, 羽毛笔",
"棉被, 泡芙",
"赛车",
"球拍",
"散热器",
"收音机",
"无线电望远镜",
"接雨水的桶",
"野营旅游车, 休闲车",
"卷轴",
"反射式照相机",
"冰箱, 冷藏库",
"遥控器",
"餐厅",
"左轮手枪, 六发式左轮手枪",
"步枪",
"摇椅",
"烤肉店, 电转烤肉架",
"橡皮",
"橄榄球",
"尺子, 标尺",
"跑步鞋",
"保险箱",
"安全别针",
"盐瓶",
"凉鞋",
"围裙",
"萨克斯管",
"鞘, 枪套",
"天平, 称量器",
"校车",
"纵帆船, 大篷车",
"记分板, 记分牌",
"屏幕, crt显示器, 投影管屏",
"螺旋, 螺丝钉",
"螺丝刀",
"安全带",
"缝纫机",
"盾牌",
"鞋店",
"障子",
"购物篮, 提篮",
"购物手推车",
"铁铲",
"浴帽",
"浴帘",
"滑雪橇",
"滑雪面罩",
"睡袋",
"计算尺",
"滑动门",
"老虎机, 游戏机",
"呼吸管, 通气管",
"雪上汽车, 机动雪橇",
"扫雪机",
"给皂器",
"英式足球",
"短袜",
"太阳能集热器, 太阳能炉",
"宽边帽, 墨西哥帽",
"汤碗",
"空格键",
"小型取暖器",
"航天飞机",
"抹刀, 小铲",
"快艇, 高速游艇",
"蜘蛛网",
"主轴, 纺锤体",
"跑车",
"聚光灯",
"舞台",
"蒸汽机车",
"钢拱桥",
"钢鼓, 钢桶",
"听诊器",
"圣衣, 女用披肩",
"石墙",
"秒表",
"烘箱, 火炉",
"过滤器",
"有轨电车",
"担架",
"沙发床",
"佛塔, 圆顶塔",
"潜艇, 救生艇",
"套装",
"日晷",
"太阳镜",
"太阳镜, 墨镜",
"防晒霜",
"吊桥",
"拖把",
"运动衫",
"游泳裤",
"秋千",
"开关",
"注射器",
"台灯",
"陆军坦克, 装甲战车",
"磁带放音机",
"茶壶",
"泰迪, 泰迪熊",
"电视, 电视系统",
"网球",
"茅草, 茅草屋顶",
"剧场幕布",
"顶针",
"脱粒机",
"王座",
"瓦屋顶",
"烤面包机, 烤箱",
"烟草商店",
"马桶座圈",
"火把, 火炬, 手电筒",
"图腾柱",
"拖车, 打捞车",
"玩具店",
"拖拉机",
"拖车, 拖拉机挂车, 铰接式货车, 半挂车",
"托盘",
"风衣",
"三轮车, 脚踏车",
"三体艇, 三体帆船",
"三脚架",
"凯旋门",
"无轨电车",
"长号, 伸缩喇叭",
"浴缸",
"验票闸门",
"打字机键盘",
"雨伞",
"独轮车",
"竖式钢琴",
"真空吸尘器",
"花瓶",
"拱顶, 撑竿跳, 跳马",
"天鹅绒",
"自动贩卖机, 自动售货机",
"作礼拜时教士的）法衣, 官服",
"高架桥",
"小提琴",
"排球",
"对开式铁心, 烘蛋奶饼的铁模",
"挂钟",
"钱包",
"衣柜",
"军用飞机",
"手盆, 脸盆",
"洗衣机",
"水瓶, 水壶",
"水壶",
"水塔",
"威士忌壶",
"汽笛",
"假发",
"纱窗, 窗格子",
"遮光窗帘, 百叶窗",
"温莎领带",
"酒瓶",
"机翼, 翅膀",
"炒锅, 炒勺",
"木匙",
"羊毛",
"蛇形栅栏, 犬牙形篱笆",
"残骸",
"船载小艇",
"蒙古包, 圆顶帐篷",
"网站",
"连环漫画册",
"纵横字谜, 填字游戏",
"路标",
"红绿灯",
"防尘罩, 书皮, 包书纸",
"菜单",
"盘子, 碟",
"鳄梨色拉酱",
"清炖肉汤",
"火锅",
"蛋糕",
"冰淇淋",
"冰棒",
"法式长棍, 法式面包",
"百吉饼",
"椒盐卷饼, 一种脆饼干",
"奶酪汉堡",
"热狗",
"土豆泥",
"卷心菜",
"花椰菜, 西兰花",
"花椰菜, 菜花",
"西葫芦",
"鱼翅瓜, 意面南瓜",
"小青南瓜",
"冬南瓜",
"黄瓜",
"朝鲜蓟, 洋蓟",
"灯笼椒, 甜椒",
"刺菜蓟",
"蘑菇",
"绿苹果",
"草莓",
"橙子, 桔子",
"柠檬",
"无花果",
"菠萝",
"香蕉",
"菠萝蜜",
"南美番荔枝",
"石榴",
"干草",
"奶油培根, 意粉, 烤面条加干酪沙司",
"巧克力酱",
"生面团, 金钱",
"肉块, 烘肉卷",
"披萨",
"肉炖面团,, 肉馅饼",
"玉米煎饼",
"红葡萄酒",
"浓咖啡",
"杯子",
"蛋酒",
"高山",
"气泡, 泡沫",
"悬崖",
"珊瑚礁",
"间歇喷泉",
"湖边",
"海角, 岬",
"沙洲",
"海岸",
"山谷",
"火山",
"棒球运动员",
"新郎",
"初级潜水员, 水肺潜水员",
"油菜籽",
"雏菊",
"黄花杓兰, 杓兰",
"玉米",
"橡子, 橡树果",
"蔷薇果, 野玫瑰果",
"七叶树",
"灵芝珊瑚",
"木耳",
"鹿花菌属",
"鬼笔菌, 腐尸真菌",
"量显地星, 地星",
"灰树花, 贝叶多孔菌, 多叶奇果菌",
"牛肝菌",
"穗, 长钉, 头状花序",
"卫生纸"
};